server:
  port: 8000

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/service_test_schema
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  properties:
    hibernate:
      format_sql: true
      dialect: org.hibernate.dialect.MySQL8Dialect

  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: my-service-client2  # Keycloak 클라이언트 ID
            client-secret: d6eglWPWDxwU0suWHPvgIqLY8zVb53rS  # Keycloak 클라이언트 비밀키
            scope: openid, profile, email
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/my-realm  # 최신 권장 방식

logging:
  level:
    org.springframework.security.oauth2.client: DEBUG
    org.springframework.security.oauth2.core: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG
    org.apache.http: DEBUG
    org:
      springframework:
        security: DEBUG

keycloak:
  realm: my-realm
  resource: my-service-client2
  credentials:
    secret: d6eglWPWDxwU0suWHPvgIqLY8zVb53rS
